// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;
import 'package:objective_c/objective_c.dart' as objc;
import 'package:ffi/ffi.dart' as pkg_ffi;

final class CGAffineTransform extends ffi.Struct {
  @ffi.Double()
  external double a;

  @ffi.Double()
  external double b;

  @ffi.Double()
  external double c;

  @ffi.Double()
  external double d;

  @ffi.Double()
  external double tx;

  @ffi.Double()
  external double ty;
}

final class CMTime extends ffi.Struct {
  @ffi.Int64()
  external int value;

  @ffi.Int32()
  external int timescale;

  @ffi.Uint32()
  external int flags;

  @ffi.Int64()
  external int epoch;
}

final class CMTimeRange extends ffi.Struct {
  external CMTime start;

  external CMTime duration;
}

enum AVAssetExportSessionStatus {
  AVAssetExportSessionStatusUnknown(0),
  AVAssetExportSessionStatusWaiting(1),
  AVAssetExportSessionStatusExporting(2),
  AVAssetExportSessionStatusCompleted(3),
  AVAssetExportSessionStatusFailed(4),
  AVAssetExportSessionStatusCancelled(5);

  final int value;
  const AVAssetExportSessionStatus(this.value);

  static AVAssetExportSessionStatus fromValue(int value) => switch (value) {
    0 => AVAssetExportSessionStatusUnknown,
    1 => AVAssetExportSessionStatusWaiting,
    2 => AVAssetExportSessionStatusExporting,
    3 => AVAssetExportSessionStatusCompleted,
    4 => AVAssetExportSessionStatusFailed,
    5 => AVAssetExportSessionStatusCancelled,
    _ => throw ArgumentError(
      'Unknown value for AVAssetExportSessionStatus: $value',
    ),
  };
}

late final _class_AVAssetTrack = objc.getClass("AVAssetTrack");
late final _sel_isKindOfClass_ = objc.registerName("isKindOfClass:");
final _objc_msgSend_19nvye5 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
late final _sel_naturalSize = objc.registerName("naturalSize");
final _objc_msgSend_a5nfga = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        objc.CGSize Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      objc.CGSize Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_a5nfgaStret = objc.msgSendStretPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.CGSize>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.CGSize>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_preferredTransform = objc.registerName("preferredTransform");
final _objc_msgSend_g23os4 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        CGAffineTransform Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      CGAffineTransform Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_g23os4Stret = objc.msgSendStretPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<CGAffineTransform>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<CGAffineTransform>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
typedef instancetype = ffi.Pointer<objc.ObjCObjectImpl>;
typedef Dartinstancetype = objc.ObjCObject;
late final _sel_alloc = objc.registerName("alloc");
final _objc_msgSend_151sglz = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_init = objc.registerName("init");

/// AVAssetTrack
extension type AVAssetTrack._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [AVAssetTrack] that points to the same underlying object as [other].
  AVAssetTrack.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [AVAssetTrack] that wraps the given raw object pointer.
  AVAssetTrack.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [AVAssetTrack].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_AVAssetTrack,
  );

  /// alloc
  static AVAssetTrack alloc() {
    final $ret = _objc_msgSend_151sglz(_class_AVAssetTrack, _sel_alloc);
    return AVAssetTrack.fromPointer($ret, retain: false, release: true);
  }
}

extension AVAssetTrack$Methods on AVAssetTrack {
  /// init
  AVAssetTrack init() {
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return AVAssetTrack.fromPointer($ret, retain: false, release: true);
  }

  /// naturalSize
  objc.CGSize get naturalSize {
    final $ptr = pkg_ffi.calloc<objc.CGSize>();
    objc.useMsgSendVariants
        ? _objc_msgSend_a5nfgaStret($ptr, object$.ref.pointer, _sel_naturalSize)
        : $ptr.ref = _objc_msgSend_a5nfga(
            object$.ref.pointer,
            _sel_naturalSize,
          );
    final $finalizable = $ptr.cast<ffi.Uint8>().asTypedList(
      ffi.sizeOf<objc.CGSize>(),
      finalizer: pkg_ffi.calloc.nativeFree,
    );
    return ffi.Struct.create<objc.CGSize>($finalizable);
  }

  /// preferredTransform
  CGAffineTransform get preferredTransform {
    final $ptr = pkg_ffi.calloc<CGAffineTransform>();
    objc.useMsgSendVariants
        ? _objc_msgSend_g23os4Stret(
            $ptr,
            object$.ref.pointer,
            _sel_preferredTransform,
          )
        : $ptr.ref = _objc_msgSend_g23os4(
            object$.ref.pointer,
            _sel_preferredTransform,
          );
    final $finalizable = $ptr.cast<ffi.Uint8>().asTypedList(
      ffi.sizeOf<CGAffineTransform>(),
      finalizer: pkg_ffi.calloc.nativeFree,
    );
    return ffi.Struct.create<CGAffineTransform>($finalizable);
  }
}

late final _class_AVAsset = objc.getClass("AVAsset");
late final _sel_tracksWithMediaType_ = objc.registerName(
  "tracksWithMediaType:",
);
final _objc_msgSend_1sotr3r = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();

/// AVAsset
extension type AVAsset._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [AVAsset] that points to the same underlying object as [other].
  AVAsset.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [AVAsset] that wraps the given raw object pointer.
  AVAsset.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [AVAsset].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_AVAsset,
  );

  /// alloc
  static AVAsset alloc() {
    final $ret = _objc_msgSend_151sglz(_class_AVAsset, _sel_alloc);
    return AVAsset.fromPointer($ret, retain: false, release: true);
  }
}

extension AVAsset$Methods on AVAsset {
  /// init
  AVAsset init() {
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return AVAsset.fromPointer($ret, retain: false, release: true);
  }

  /// tracksWithMediaType:
  objc.NSArray tracksWithMediaType(objc.NSString mediaType) {
    final $ret = _objc_msgSend_1sotr3r(
      object$.ref.pointer,
      _sel_tracksWithMediaType_,
      mediaType.ref.pointer,
    );
    return objc.NSArray.fromPointer($ret, retain: true, release: true);
  }
}

late final _class_AVURLAsset = objc.getClass("AVURLAsset");
late final _sel_URLAssetWithURL_options_ = objc.registerName(
  "URLAssetWithURL:options:",
);
final _objc_msgSend_15qeuct = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();

/// AVURLAsset
extension type AVURLAsset._(objc.ObjCObject object$)
    implements objc.ObjCObject, AVAsset {
  /// Constructs a [AVURLAsset] that points to the same underlying object as [other].
  AVURLAsset.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [AVURLAsset] that wraps the given raw object pointer.
  AVURLAsset.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [AVURLAsset].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_AVURLAsset,
  );

  /// URLAssetWithURL:options:
  static AVURLAsset URLAssetWithURL(
    objc.NSURL URL, {
    required objc.NSDictionary options,
  }) {
    final $ret = _objc_msgSend_15qeuct(
      _class_AVURLAsset,
      _sel_URLAssetWithURL_options_,
      URL.ref.pointer,
      options.ref.pointer,
    );
    return AVURLAsset.fromPointer($ret, retain: true, release: true);
  }

  /// alloc
  static AVURLAsset alloc() {
    final $ret = _objc_msgSend_151sglz(_class_AVURLAsset, _sel_alloc);
    return AVURLAsset.fromPointer($ret, retain: false, release: true);
  }
}

extension AVURLAsset$Methods on AVURLAsset {
  /// init
  AVURLAsset init() {
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return AVURLAsset.fromPointer($ret, retain: false, release: true);
  }
}

late final _class_AVVideoCompositionInstruction = objc.getClass(
  "AVVideoCompositionInstruction",
);

/// AVVideoCompositionInstruction
extension type AVVideoCompositionInstruction._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [AVVideoCompositionInstruction] that points to the same underlying object as [other].
  AVVideoCompositionInstruction.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [AVVideoCompositionInstruction] that wraps the given raw object pointer.
  AVVideoCompositionInstruction.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [AVVideoCompositionInstruction].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_AVVideoCompositionInstruction,
  );

  /// alloc
  static AVVideoCompositionInstruction alloc() {
    final $ret = _objc_msgSend_151sglz(
      _class_AVVideoCompositionInstruction,
      _sel_alloc,
    );
    return AVVideoCompositionInstruction.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }
}

extension AVVideoCompositionInstruction$Methods
    on AVVideoCompositionInstruction {
  /// init
  AVVideoCompositionInstruction init() {
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return AVVideoCompositionInstruction.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }
}

late final _class_AVMutableVideoCompositionInstruction = objc.getClass(
  "AVMutableVideoCompositionInstruction",
);
late final _sel_timeRange = objc.registerName("timeRange");
final _objc_msgSend_rynxlp = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        CMTimeRange Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      CMTimeRange Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_rynxlpStret = objc.msgSendStretPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<CMTimeRange>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<CMTimeRange>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_setTimeRange_ = objc.registerName("setTimeRange:");
final _objc_msgSend_1k8xwk9 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          CMTimeRange,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        CMTimeRange,
      )
    >();
late final _sel_layerInstructions = objc.registerName("layerInstructions");
late final _sel_setLayerInstructions_ = objc.registerName(
  "setLayerInstructions:",
);
final _objc_msgSend_xtuoz7 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
late final _sel_videoCompositionInstruction = objc.registerName(
  "videoCompositionInstruction",
);

/// AVMutableVideoCompositionInstruction
extension type AVMutableVideoCompositionInstruction._(objc.ObjCObject object$)
    implements objc.ObjCObject, AVVideoCompositionInstruction {
  /// Constructs a [AVMutableVideoCompositionInstruction] that points to the same underlying object as [other].
  AVMutableVideoCompositionInstruction.as(objc.ObjCObject other)
    : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [AVMutableVideoCompositionInstruction] that wraps the given raw object pointer.
  AVMutableVideoCompositionInstruction.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [AVMutableVideoCompositionInstruction].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_AVMutableVideoCompositionInstruction,
  );

  /// alloc
  static AVMutableVideoCompositionInstruction alloc() {
    final $ret = _objc_msgSend_151sglz(
      _class_AVMutableVideoCompositionInstruction,
      _sel_alloc,
    );
    return AVMutableVideoCompositionInstruction.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// videoCompositionInstruction
  static AVMutableVideoCompositionInstruction videoCompositionInstruction() {
    final $ret = _objc_msgSend_151sglz(
      _class_AVMutableVideoCompositionInstruction,
      _sel_videoCompositionInstruction,
    );
    return AVMutableVideoCompositionInstruction.fromPointer(
      $ret,
      retain: true,
      release: true,
    );
  }
}

extension AVMutableVideoCompositionInstruction$Methods
    on AVMutableVideoCompositionInstruction {
  /// init
  AVMutableVideoCompositionInstruction init() {
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return AVMutableVideoCompositionInstruction.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// layerInstructions
  objc.NSArray get layerInstructions {
    final $ret = _objc_msgSend_151sglz(
      object$.ref.pointer,
      _sel_layerInstructions,
    );
    return objc.NSArray.fromPointer($ret, retain: true, release: true);
  }

  /// setLayerInstructions:
  set layerInstructions(objc.NSArray value) {
    _objc_msgSend_xtuoz7(
      object$.ref.pointer,
      _sel_setLayerInstructions_,
      value.ref.pointer,
    );
  }

  /// setTimeRange:
  set timeRange(CMTimeRange value) {
    _objc_msgSend_1k8xwk9(object$.ref.pointer, _sel_setTimeRange_, value);
  }

  /// timeRange
  CMTimeRange get timeRange {
    final $ptr = pkg_ffi.calloc<CMTimeRange>();
    objc.useMsgSendVariants
        ? _objc_msgSend_rynxlpStret($ptr, object$.ref.pointer, _sel_timeRange)
        : $ptr.ref = _objc_msgSend_rynxlp(object$.ref.pointer, _sel_timeRange);
    final $finalizable = $ptr.cast<ffi.Uint8>().asTypedList(
      ffi.sizeOf<CMTimeRange>(),
      finalizer: pkg_ffi.calloc.nativeFree,
    );
    return ffi.Struct.create<CMTimeRange>($finalizable);
  }
}

late final _class_AVVideoCompositionLayerInstruction = objc.getClass(
  "AVVideoCompositionLayerInstruction",
);

/// AVVideoCompositionLayerInstruction
extension type AVVideoCompositionLayerInstruction._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [AVVideoCompositionLayerInstruction] that points to the same underlying object as [other].
  AVVideoCompositionLayerInstruction.as(objc.ObjCObject other)
    : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [AVVideoCompositionLayerInstruction] that wraps the given raw object pointer.
  AVVideoCompositionLayerInstruction.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [AVVideoCompositionLayerInstruction].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_AVVideoCompositionLayerInstruction,
  );

  /// alloc
  static AVVideoCompositionLayerInstruction alloc() {
    final $ret = _objc_msgSend_151sglz(
      _class_AVVideoCompositionLayerInstruction,
      _sel_alloc,
    );
    return AVVideoCompositionLayerInstruction.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }
}

extension AVVideoCompositionLayerInstruction$Methods
    on AVVideoCompositionLayerInstruction {
  /// init
  AVVideoCompositionLayerInstruction init() {
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return AVVideoCompositionLayerInstruction.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }
}

late final _class_AVMutableVideoCompositionLayerInstruction = objc.getClass(
  "AVMutableVideoCompositionLayerInstruction",
);
late final _sel_videoCompositionLayerInstructionWithAssetTrack_ = objc
    .registerName("videoCompositionLayerInstructionWithAssetTrack:");
late final _sel_setTransform_atTime_ = objc.registerName(
  "setTransform:atTime:",
);
final _objc_msgSend_18vwxch = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          CGAffineTransform,
          CMTime,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        CGAffineTransform,
        CMTime,
      )
    >();

/// AVMutableVideoCompositionLayerInstruction
extension type AVMutableVideoCompositionLayerInstruction._(
  objc.ObjCObject object$
)
    implements objc.ObjCObject, AVVideoCompositionLayerInstruction {
  /// Constructs a [AVMutableVideoCompositionLayerInstruction] that points to the same underlying object as [other].
  AVMutableVideoCompositionLayerInstruction.as(objc.ObjCObject other)
    : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [AVMutableVideoCompositionLayerInstruction] that wraps the given raw object pointer.
  AVMutableVideoCompositionLayerInstruction.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [AVMutableVideoCompositionLayerInstruction].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_AVMutableVideoCompositionLayerInstruction,
  );

  /// alloc
  static AVMutableVideoCompositionLayerInstruction alloc() {
    final $ret = _objc_msgSend_151sglz(
      _class_AVMutableVideoCompositionLayerInstruction,
      _sel_alloc,
    );
    return AVMutableVideoCompositionLayerInstruction.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// videoCompositionLayerInstructionWithAssetTrack:
  static AVMutableVideoCompositionLayerInstruction
  videoCompositionLayerInstructionWithAssetTrack(AVAssetTrack track) {
    final $ret = _objc_msgSend_1sotr3r(
      _class_AVMutableVideoCompositionLayerInstruction,
      _sel_videoCompositionLayerInstructionWithAssetTrack_,
      track.ref.pointer,
    );
    return AVMutableVideoCompositionLayerInstruction.fromPointer(
      $ret,
      retain: true,
      release: true,
    );
  }
}

extension AVMutableVideoCompositionLayerInstruction$Methods
    on AVMutableVideoCompositionLayerInstruction {
  /// init
  AVMutableVideoCompositionLayerInstruction init() {
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return AVMutableVideoCompositionLayerInstruction.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// setTransform:atTime:
  void setTransform(CGAffineTransform transform, {required CMTime atTime}) {
    _objc_msgSend_18vwxch(
      object$.ref.pointer,
      _sel_setTransform_atTime_,
      transform,
      atTime,
    );
  }
}

late final _class_AVVideoComposition = objc.getClass("AVVideoComposition");

/// AVVideoComposition
extension type AVVideoComposition._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [AVVideoComposition] that points to the same underlying object as [other].
  AVVideoComposition.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [AVVideoComposition] that wraps the given raw object pointer.
  AVVideoComposition.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [AVVideoComposition].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_AVVideoComposition,
  );

  /// alloc
  static AVVideoComposition alloc() {
    final $ret = _objc_msgSend_151sglz(_class_AVVideoComposition, _sel_alloc);
    return AVVideoComposition.fromPointer($ret, retain: false, release: true);
  }
}

extension AVVideoComposition$Methods on AVVideoComposition {
  /// init
  AVVideoComposition init() {
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return AVVideoComposition.fromPointer($ret, retain: false, release: true);
  }
}

late final _class_AVMutableVideoComposition = objc.getClass(
  "AVMutableVideoComposition",
);
late final _sel_instructions = objc.registerName("instructions");
late final _sel_setInstructions_ = objc.registerName("setInstructions:");
late final _sel_customVideoCompositorClass = objc.registerName(
  "customVideoCompositorClass",
);
late final _sel_setCustomVideoCompositorClass_ = objc.registerName(
  "setCustomVideoCompositorClass:",
);
late final _sel_frameDuration = objc.registerName("frameDuration");
final _objc_msgSend_1f8hvjs = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        CMTime Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      CMTime Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_1f8hvjsStret = objc.msgSendStretPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<CMTime>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<CMTime>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_setFrameDuration_ = objc.registerName("setFrameDuration:");
final _objc_msgSend_1hznzoi = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          CMTime,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        CMTime,
      )
    >();
late final _sel_renderSize = objc.registerName("renderSize");
late final _sel_setRenderSize_ = objc.registerName("setRenderSize:");
final _objc_msgSend_bfocsk = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          objc.CGSize,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        objc.CGSize,
      )
    >();
late final _sel_renderScale = objc.registerName("renderScale");
final _objc_msgSend_2cgrxl = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Float Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      double Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_2cgrxlFpret = objc.msgSendFpretPointer
    .cast<
      ffi.NativeFunction<
        ffi.Float Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      double Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_setRenderScale_ = objc.registerName("setRenderScale:");
final _objc_msgSend_v5hmet = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Float,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        double,
      )
    >();
late final _sel_videoComposition = objc.registerName("videoComposition");

/// AVMutableVideoComposition
extension type AVMutableVideoComposition._(objc.ObjCObject object$)
    implements objc.ObjCObject, AVVideoComposition {
  /// Constructs a [AVMutableVideoComposition] that points to the same underlying object as [other].
  AVMutableVideoComposition.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [AVMutableVideoComposition] that wraps the given raw object pointer.
  AVMutableVideoComposition.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [AVMutableVideoComposition].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_AVMutableVideoComposition,
  );

  /// alloc
  static AVMutableVideoComposition alloc() {
    final $ret = _objc_msgSend_151sglz(
      _class_AVMutableVideoComposition,
      _sel_alloc,
    );
    return AVMutableVideoComposition.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// videoComposition
  static AVMutableVideoComposition videoComposition() {
    final $ret = _objc_msgSend_151sglz(
      _class_AVMutableVideoComposition,
      _sel_videoComposition,
    );
    return AVMutableVideoComposition.fromPointer(
      $ret,
      retain: true,
      release: true,
    );
  }
}

extension AVMutableVideoComposition$Methods on AVMutableVideoComposition {
  /// customVideoCompositorClass
  objc.ObjCObject get customVideoCompositorClass {
    final $ret = _objc_msgSend_151sglz(
      object$.ref.pointer,
      _sel_customVideoCompositorClass,
    );
    return objc.ObjCObject($ret, retain: true, release: true);
  }

  /// frameDuration
  CMTime get frameDuration {
    final $ptr = pkg_ffi.calloc<CMTime>();
    objc.useMsgSendVariants
        ? _objc_msgSend_1f8hvjsStret(
            $ptr,
            object$.ref.pointer,
            _sel_frameDuration,
          )
        : $ptr.ref = _objc_msgSend_1f8hvjs(
            object$.ref.pointer,
            _sel_frameDuration,
          );
    final $finalizable = $ptr.cast<ffi.Uint8>().asTypedList(
      ffi.sizeOf<CMTime>(),
      finalizer: pkg_ffi.calloc.nativeFree,
    );
    return ffi.Struct.create<CMTime>($finalizable);
  }

  /// init
  AVMutableVideoComposition init() {
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return AVMutableVideoComposition.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// instructions
  objc.NSArray get instructions {
    final $ret = _objc_msgSend_151sglz(object$.ref.pointer, _sel_instructions);
    return objc.NSArray.fromPointer($ret, retain: true, release: true);
  }

  /// renderScale
  double get renderScale {
    return objc.useMsgSendVariants
        ? _objc_msgSend_2cgrxlFpret(object$.ref.pointer, _sel_renderScale)
        : _objc_msgSend_2cgrxl(object$.ref.pointer, _sel_renderScale);
  }

  /// renderSize
  objc.CGSize get renderSize {
    final $ptr = pkg_ffi.calloc<objc.CGSize>();
    objc.useMsgSendVariants
        ? _objc_msgSend_a5nfgaStret($ptr, object$.ref.pointer, _sel_renderSize)
        : $ptr.ref = _objc_msgSend_a5nfga(object$.ref.pointer, _sel_renderSize);
    final $finalizable = $ptr.cast<ffi.Uint8>().asTypedList(
      ffi.sizeOf<objc.CGSize>(),
      finalizer: pkg_ffi.calloc.nativeFree,
    );
    return ffi.Struct.create<objc.CGSize>($finalizable);
  }

  /// setCustomVideoCompositorClass:
  set customVideoCompositorClass(objc.ObjCObject value) {
    _objc_msgSend_xtuoz7(
      object$.ref.pointer,
      _sel_setCustomVideoCompositorClass_,
      value.ref.pointer,
    );
  }

  /// setFrameDuration:
  set frameDuration(CMTime value) {
    _objc_msgSend_1hznzoi(object$.ref.pointer, _sel_setFrameDuration_, value);
  }

  /// setInstructions:
  set instructions(objc.NSArray value) {
    _objc_msgSend_xtuoz7(
      object$.ref.pointer,
      _sel_setInstructions_,
      value.ref.pointer,
    );
  }

  /// setRenderScale:
  set renderScale(double value) {
    _objc_msgSend_v5hmet(object$.ref.pointer, _sel_setRenderScale_, value);
  }

  /// setRenderSize:
  set renderSize(objc.CGSize value) {
    _objc_msgSend_bfocsk(object$.ref.pointer, _sel_setRenderSize_, value);
  }
}

late final _class_AVAssetExportSession = objc.getClass("AVAssetExportSession");
late final _sel_exportSessionWithAsset_presetName_ = objc.registerName(
  "exportSessionWithAsset:presetName:",
);
late final _sel_outputURL = objc.registerName("outputURL");
late final _sel_setOutputURL_ = objc.registerName("setOutputURL:");
late final _sel_outputFileType = objc.registerName("outputFileType");
late final _sel_setOutputFileType_ = objc.registerName("setOutputFileType:");
late final _sel_setVideoComposition_ = objc.registerName(
  "setVideoComposition:",
);
late final _sel_exportAsynchronouslyWithCompletionHandler_ = objc.registerName(
  "exportAsynchronouslyWithCompletionHandler:",
);
final _objc_msgSend_ovsamd = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<ffi.Void>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<ffi.Void>,
      )
    >();
late final _sel_status = objc.registerName("status");
final _objc_msgSend_195k4xu = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.UnsignedInt Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      int Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_error = objc.registerName("error");

/// AVAssetExportSession
extension type AVAssetExportSession._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [AVAssetExportSession] that points to the same underlying object as [other].
  AVAssetExportSession.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [AVAssetExportSession] that wraps the given raw object pointer.
  AVAssetExportSession.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [AVAssetExportSession].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_AVAssetExportSession,
  );

  /// alloc
  static AVAssetExportSession alloc() {
    final $ret = _objc_msgSend_151sglz(_class_AVAssetExportSession, _sel_alloc);
    return AVAssetExportSession.fromPointer($ret, retain: false, release: true);
  }

  /// exportSessionWithAsset:presetName:
  static AVAssetExportSession exportSessionWithAsset(
    AVAsset asset, {
    required objc.NSString presetName,
  }) {
    final $ret = _objc_msgSend_15qeuct(
      _class_AVAssetExportSession,
      _sel_exportSessionWithAsset_presetName_,
      asset.ref.pointer,
      presetName.ref.pointer,
    );
    return AVAssetExportSession.fromPointer($ret, retain: true, release: true);
  }
}

extension AVAssetExportSession$Methods on AVAssetExportSession {
  /// error
  objc.NSError get error {
    final $ret = _objc_msgSend_151sglz(object$.ref.pointer, _sel_error);
    return objc.NSError.fromPointer($ret, retain: true, release: true);
  }

  /// exportAsynchronouslyWithCompletionHandler:
  void exportAsynchronouslyWithCompletionHandler(
    ffi.Pointer<ffi.Void> handler,
  ) {
    _objc_msgSend_ovsamd(
      object$.ref.pointer,
      _sel_exportAsynchronouslyWithCompletionHandler_,
      handler,
    );
  }

  /// init
  AVAssetExportSession init() {
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return AVAssetExportSession.fromPointer($ret, retain: false, release: true);
  }

  /// outputFileType
  objc.NSString get outputFileType {
    final $ret = _objc_msgSend_151sglz(
      object$.ref.pointer,
      _sel_outputFileType,
    );
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// outputURL
  objc.NSURL get outputURL {
    final $ret = _objc_msgSend_151sglz(object$.ref.pointer, _sel_outputURL);
    return objc.NSURL.fromPointer($ret, retain: true, release: true);
  }

  /// setOutputFileType:
  set outputFileType(objc.NSString value) {
    _objc_msgSend_xtuoz7(
      object$.ref.pointer,
      _sel_setOutputFileType_,
      value.ref.pointer,
    );
  }

  /// setOutputURL:
  set outputURL(objc.NSURL value) {
    _objc_msgSend_xtuoz7(
      object$.ref.pointer,
      _sel_setOutputURL_,
      value.ref.pointer,
    );
  }

  /// setTimeRange:
  set timeRange(CMTimeRange value) {
    _objc_msgSend_1k8xwk9(object$.ref.pointer, _sel_setTimeRange_, value);
  }

  /// setVideoComposition:
  set videoComposition(AVVideoComposition value) {
    _objc_msgSend_xtuoz7(
      object$.ref.pointer,
      _sel_setVideoComposition_,
      value.ref.pointer,
    );
  }

  /// status
  AVAssetExportSessionStatus get status {
    final $ret = _objc_msgSend_195k4xu(object$.ref.pointer, _sel_status);
    return AVAssetExportSessionStatus.fromValue($ret);
  }

  /// timeRange
  CMTimeRange get timeRange {
    final $ptr = pkg_ffi.calloc<CMTimeRange>();
    objc.useMsgSendVariants
        ? _objc_msgSend_rynxlpStret($ptr, object$.ref.pointer, _sel_timeRange)
        : $ptr.ref = _objc_msgSend_rynxlp(object$.ref.pointer, _sel_timeRange);
    final $finalizable = $ptr.cast<ffi.Uint8>().asTypedList(
      ffi.sizeOf<CMTimeRange>(),
      finalizer: pkg_ffi.calloc.nativeFree,
    );
    return ffi.Struct.create<CMTimeRange>($finalizable);
  }

  /// videoComposition
  AVVideoComposition get videoComposition {
    final $ret = _objc_msgSend_151sglz(
      object$.ref.pointer,
      _sel_videoComposition,
    );
    return AVVideoComposition.fromPointer($ret, retain: true, release: true);
  }
}
